// All 16 regions and their districts/municipalities, used to populate the
// Region and District pickers on the sign-up form.

export const GHANA_DISTRICTS_BY_REGION: Record<string, string[]> = {
  Ahafo: [
    'Asunafo North Municipal',
    'Asunafo South',
    'Asutifi North',
    'Asutifi South',
    'Tano North Municipal',
    'Tano South Municipal',
  ],
  Ashanti: [
    'Adansi Akrofuom',
    'Adansi Asokwa',
    'Adansi North',
    'Adansi South',
    'Afigya Kwabre North',
    'Afigya Kwabre South',
    'Ahafo Ano North',
    'Ahafo Ano South East',
    'Ahafo Ano South West',
    'Amansie Central',
    'Amansie South',
    'Amansie West',
    'Asante Akim Central Municipal',
    'Asante Akim North',
    'Asante Akim South',
    'Asokore Mampong Municipal',
    'Asokwa Municipal',
    'Atwima Kwanwoma',
    'Atwima Mponua',
    'Atwima Nwabiagya North',
    'Atwima Nwabiagya South',
    'Bekwai Municipal',
    'Bosome Freho',
    'Bosomtwe',
    'Ejisu Municipal',
    'Ejura-Sekyedumase',
    'Juaben Municipal',
    'Kumasi Metropolitan',
    'Kwabre East',
    'Kwadaso Municipal',
    'Mampong Municipal',
    'Obuasi East',
    'Obuasi Municipal',
    'Offinso Municipal',
    'Offinso North',
    'Oforikrom Municipal',
    'Old Tafo Municipal',
    'Sekyere Afram Plains North',
    'Sekyere Central',
    'Sekyere East',
    'Sekyere Kumawu',
    'Sekyere South',
    'Suame Municipal',
  ],
  Bono: [
    'Banda',
    'Berekum East Municipal',
    'Berekum West',
    'Dormaa East',
    'Dormaa Municipal',
    'Dormaa West',
    'Jaman North',
    'Jaman South Municipal',
    'Sunyani Municipal',
    'Sunyani West',
    'Tain',
    'Wenchi Municipal',
  ],
  'Bono East': [
    'Atebubu-Amantin',
    'Kintampo North Municipal',
    'Kintampo South',
    'Nkoranza North',
    'Nkoranza South',
    'Pru East',
    'Pru West',
    'Sene East',
    'Sene West',
    'Techiman Municipal',
    'Techiman North',
  ],
  Central: [
    'Abura-Asebu-Kwamankese',
    'Agona East',
    'Agona West Municipal',
    'Ajumako-Enyan-Essiam',
    'Asikuma-Odoben-Brakwa',
    'Assin Central Municipal',
    'Assin North',
    'Assin South',
    'Awutu Senya',
    'Awutu Senya East',
    'Cape Coast Metropolitan',
    'Effutu Municipal',
    'Ekumfi',
    'Gomoa Central',
    'Gomoa East',
    'Gomoa West',
    'Komenda-Edina-Eguafo-Abirem Municipal',
    'Mfantseman Municipal',
    'Twifo Atti-Morkwa',
    'Twifo Hemang Lower Denkyira',
    'Upper Denkyira East Municipal',
    'Upper Denkyira West',
  ],
  Eastern: [
    'Abuakwa North',
    'Abuakwa South',
    'Achiase',
    'Akwapim North',
    'Akwapim South',
    'Akyemansa',
    'Asene Akroso Manso',
    'Asuogyaman',
    'Atiwa East',
    'Atiwa West',
    'Ayensuano',
    'Birim Central Municipal',
    'Birim North',
    'Birim South',
    'Denkyembour',
    'Fanteakwa North',
    'Fanteakwa South',
    'Kwaebibirem Municipal',
    'Kwahu Afram Plains North',
    'Kwahu Afram Plains South',
    'Kwahu East',
    'Kwahu South',
    'Kwahu West Municipal',
    'Lower Manya Krobo Municipal',
    'New Juaben North Municipal',
    'New Juaben South Municipal',
    'Nsawam Adoagyiri Municipal',
    'Okere',
    'Suhum Municipal',
    'Upper Manya Krobo',
    'Upper West Akim',
    'West Akim Municipal',
    'Yilo Krobo Municipal',
  ],
  'Greater Accra': [
    'Ablekuma Central Municipal',
    'Ablekuma North Municipal',
    'Ablekuma West Municipal',
    'Accra Metropolitan',
    'Ada East',
    'Ada West',
    'Adentan Municipal',
    'Ashaiman Municipal',
    'Ayawaso Central Municipal',
    'Ayawaso East Municipal',
    'Ayawaso North Municipal',
    'Ayawaso West Municipal',
    'Ga Central Municipal',
    'Ga East Municipal',
    'Ga North Municipal',
    'Ga South Municipal',
    'Ga West Municipal',
    'Korle Klottey Municipal',
    'Kpone Katamanso Municipal',
    'Krowor Municipal',
    'La Dade-Kotopon Municipal',
    'La-Nkwantanang-Madina Municipal',
    'Ledzokuku Municipal',
    'Ningo Prampram',
    'Okaikwei North Municipal',
    'Shai Osudoku',
    'Tema Metropolitan',
    'Tema West Municipal',
    'Weija Gbawe Municipal',
  ],
  'North East': [
    'Bunkpurugu-Nakpanduri',
    'Chereponi',
    'East Mamprusi Municipal',
    'Mamprugu Moagduri',
    'West Mamprusi Municipal',
    'Yunyoo-Nasuan',
  ],
  Northern: [
    'Gushegu Municipal',
    'Karaga',
    'Kpandai',
    'Kumbungu',
    'Mion',
    'Nanton',
    'Nanumba North Municipal',
    'Nanumba South',
    'Saboba',
    'Sagnarigu Municipal',
    'Savelugu Municipal',
    'Tamale Metropolitan',
    'Tatale Sanguli',
    'Tolon',
    'Yendi Municipal',
    'Zabzugu',
  ],
  Oti: [
    'Biakoye',
    'Jasikan',
    'Kadjebi',
    'Krachi East Municipal',
    'Krachi Nchumuru',
    'Krachi West',
    'Nkwanta North',
    'Nkwanta South Municipal',
  ],
  Savannah: [
    'Bole',
    'Central Gonja',
    'East Gonja Municipal',
    'North East Gonja',
    'North Gonja',
    'Sawla-Tuna-Kalba',
    'West Gonja',
  ],
  'Upper East': [
    'Bawku Municipal',
    'Bawku West',
    'Binduri',
    'Bolgatanga East',
    'Bolgatanga Municipal',
    'Bongo',
    'Builsa North Municipal',
    'Builsa South',
    'Garu',
    'Kassena Nankana Municipal',
    'Kassena Nankana West',
    'Nabdam',
    'Pusiga',
    'Talensi',
    'Tempane',
  ],
  'Upper West': [
    'Daffiama Bussie Issa',
    'Jirapa Municipal',
    'Lambussie Karni',
    'Lawra Municipal',
    'Nadowli-Kaleo',
    'Nandom Municipal',
    'Sissala East Municipal',
    'Sissala West',
    'Wa East',
    'Wa Municipal',
    'Wa West',
  ],
  Volta: [
    'Adaklu',
    'Afadzato South',
    'Agotime Ziope',
    'Akatsi North',
    'Akatsi South',
    'Anloga',
    'Central Tongu',
    'Ho Municipal',
    'Ho West',
    'Hohoe Municipal',
    'Keta Municipal',
    'Ketu North Municipal',
    'Ketu South Municipal',
    'Kpando Municipal',
    'North Dayi',
    'North Tongu',
    'South Dayi',
    'South Tongu',
  ],
  Western: [
    'Ahanta West Municipal',
    'Effia Kwesimintsim Municipal',
    'Ellembelle',
    'Jomoro Municipal',
    'Mpohor',
    'Nzema East Municipal',
    'Prestea Huni-Valley Municipal',
    'Sekondi-Takoradi Metropolitan',
    'Shama',
    'Tarkwa-Nsuaem Municipal',
    'Wassa Amenfi Central',
    'Wassa Amenfi East Municipal',
    'Wassa Amenfi West',
    'Wassa East',
  ],
  'Western North': [
    'Aowin Municipal',
    'Bia East',
    'Bia West',
    'Bibiani Anhwiaso Bekwai Municipal',
    'Bodi',
    'Juaboso',
    'Sefwi Akontombra',
    'Sefwi Wiawso Municipal',
    'Suaman',
  ],
};

export const GHANA_REGIONS: string[] = Object.keys(GHANA_DISTRICTS_BY_REGION);
